import { Scheme } from './types';

export const RECOMMENDED_SCHEMES: Scheme[] = [
  {
    id: '1',
    title: 'National Scholarship for Students',
    department: 'Ministry of Education',
    description: 'Scholarship for meritorious students across India.',
    eligibility: 'Students scoring above 80% in Class 12',
    link: 'https://scholarships.gov.in',
    category: 'Student',
    tags: ['student', 'urgent'],
    type: 'Scholarship',
  },
  {
    id: '2',
    title: 'PM Kisan Scheme',
    department: 'Ministry of Agriculture',
    description: 'Direct income support for farmers.',
    eligibility: 'Small and marginal farmers',
    link: 'https://pmkisan.gov.in',
    category: 'Farmer',
    tags: ['farmer'],
    type: 'Farmer Loan',
  },
  {
    id: '3',
    title: 'Mahila Samman Yojana',
    department: 'Women & Child Development',
    description: 'Support scheme for women entrepreneurs.',
    eligibility: 'Women aged 18-40 with a business idea',
    link: 'https://wcd.nic.in',
    category: 'Women',
    tags: ['women'],
    type: 'Women Support',
  },
  {
    id: '4',
    title: 'Central Sector Scholarship',
    department: 'Department of Higher Education',
    description: '₹10,000 - ₹20,000 per annum for meritorious college students.',
    eligibility: 'Family income < ₹8L, age 17-22',
    link: 'https://scholarships.gov.in/',
    category: 'Scholarship',
    tags: ['college', 'merit'],
    type: 'Scholarship',
  },
  {
    id: '5',
    title: 'AICTE Pragati Scholarship for Girls',
    department: 'AICTE',
    description: '₹50,000 per annum for girl students in technical courses.',
    eligibility: 'Girls enrolled in B.Tech/B.E., income < ₹8L',
    link: 'https://www.aicte-india.org/schemes/students-development-schemes/Pragati',
    category: 'Scholarship',
    tags: ['girls', 'engineering'],
    type: 'Scholarship',
  },
  {
    id: '6',
    title: 'PM YASASVI Scheme',
    department: 'Ministry of Social Justice & Empowerment',
    description: 'Up to ₹1.25 lakh for OBC, EBC, and DNT students.',
    eligibility: 'OBC/EBC/DNT, income < ₹2.5L',
    link: 'https://yet.nta.ac.in/',
    category: 'Scholarship',
    tags: ['obc', 'minority'],
    type: 'Scholarship',
  },
  {
    id: '7',
    title: 'UP Post Matric Scholarship',
    department: 'Government of Uttar Pradesh',
    description: 'Financial aid for UP students in higher education.',
    eligibility: 'Residents of UP, income < ₹2L',
    link: 'https://scholarship.up.gov.in/',
    category: 'Scholarship',
    tags: ['state', 'up'],
    type: 'Scholarship',
  },
  {
    id: '8',
    title: 'NTSE Scholarship',
    department: 'NCERT',
    description: '₹1,250 - ₹2,000 per month for Class 10 students.',
    eligibility: 'Class 10 students qualifying NTSE exam',
    link: 'https://ncert.nic.in',
    category: 'Scholarship',
    tags: ['school', 'merit'],
    type: 'Scholarship',
  },
  {
    id: '9',
    title: 'INSPIRE Scholarship',
    department: 'DST',
    description: '₹80,000 per annum for science students.',
    eligibility: 'B.Sc./M.Sc. students, income < ₹8L',
    link: 'https://online-inspire.gov.in/',
    category: 'Scholarship',
    tags: ['science'],
    type: 'Scholarship',
  },
  {
    id: '10',
    title: 'KVPY Scholarship',
    department: 'DST',
    description: '₹5,000 - ₹7,000 per month for science streams.',
    eligibility: 'B.Sc./B.Stat students qualifying KVPY',
    link: 'http://kvpy.iisc.ernet.in/',
    category: 'Scholarship',
    tags: ['research'],
    type: 'Scholarship',
  },
  {
    id: '11',
    title: 'Saksham Scholarship',
    department: 'AICTE',
    description: '₹50,000 per year for differently-abled engineering students.',
    eligibility: 'Disability + B.Tech enrollment',
    link: 'https://aicte-india.org/schemes/students-development-schemes/Saksham',
    category: 'Scholarship',
    tags: ['disability'],
    type: 'Scholarship',
  },
  {
    id: '12',
    title: 'National Fellowship for OBC',
    department: 'UGC',
    description: '₹25,000 monthly fellowship for OBC students.',
    eligibility: 'OBC category postgraduates',
    link: 'https://ugc.ac.in',
    category: 'Scholarship',
    tags: ['obc'],
    type: 'Scholarship',
  },
  {
    id: '13',
    title: 'Maulana Azad Fellowship',
    department: 'Ministry of Minority Affairs',
    description: '₹28,000 per month for minority students.',
    eligibility: 'Muslim/Christian/Sikh/Buddhist/Parsi students',
    link: 'https://minorityaffairs.gov.in',
    category: 'Scholarship',
    tags: ['minority'],
    type: 'Scholarship',
  },
  {
    id: '14',
    title: 'Begum Hazrat Mahal Scholarship',
    department: 'MAEF',
    description: 'Up to ₹12,000 for female minority students.',
    eligibility: 'Female + minority category',
    link: 'https://maef.nic.in',
    category: 'Scholarship',
    tags: ['female'],
    type: 'Scholarship',
  },
  {
    id: '15',
    title: 'National Means-cum-Merit Scholarship',
    department: 'MHRD',
    description: '₹12,000 per year for Class 8 students.',
    eligibility: 'Income < ₹1.5L + Class 8',
    link: 'https://scholarships.gov.in',
    category: 'Scholarship',
    tags: ['school'],
    type: 'Scholarship',
  },
  {
    id: '16',
    title: 'ISHAN UDAY Scholarship',
    department: 'UGC',
    description: '₹5,400–₹7,800 monthly for NE students.',
    eligibility: 'Resident of North Eastern Region',
    link: 'https://ugc.ac.in',
    category: 'Scholarship',
    tags: ['northeast'],
    type: 'Scholarship',
  },
  {
    id: '17',
    title: 'PMRF',
    department: 'Ministry of Education',
    description: '₹70,000 monthly for PhD students.',
    eligibility: 'PhD in top institutes',
    link: 'https://pmrf.in',
    category: 'Scholarship',
    tags: ['phd'],
    type: 'Scholarship',
  },
  {
    id: '18',
    title: 'AIIMS Fellowship',
    department: 'AIIMS',
    description: '₹25,000 monthly for MD/MS students.',
    eligibility: 'Medical postgraduates',
    link: 'https://aiimsexams.ac.in',
    category: 'Scholarship',
    tags: ['medical'],
    type: 'Scholarship',
  },
  {
    id: '19',
    title: 'CSIR NET JRF',
    department: 'CSIR',
    description: '₹31,000/month fellowship for science postgrads.',
    eligibility: 'M.Sc. + NET qualified',
    link: 'https://csirnet.nta.ac.in',
    category: 'Scholarship',
    tags: ['jrf'],
    type: 'Scholarship',
  },
  {
    id: '20',
    title: 'UGC NET JRF',
    department: 'UGC',
    description: '₹31,000/month fellowship for postgrads.',
    eligibility: 'MA/M.Com/M.Sc. + NET',
    link: 'https://ugcnet.nta.nic.in',
    category: 'Scholarship',
    tags: ['ugc'],
    type: 'Scholarship',
  },
  {
    id: '21',
    title: 'LIC Golden Jubilee Scholarship',
    department: 'LIC',
    description: '₹10,000 annually for low-income families.',
    eligibility: 'Income < ₹2L',
    link: 'https://licindia.in',
    category: 'Scholarship',
    tags: ['lic'],
    type: 'Scholarship',
  },
  {
    id: '22',
    title: 'Siemens Scholarship',
    department: 'Siemens India',
    description: '₹75,000 per year for B.E./B.Tech students.',
    eligibility: 'Meritorious engineering students',
    link: 'https://www.siemens.co.in',
    category: 'Scholarship',
    tags: ['engineering'],
    type: 'Scholarship',
  },
  {
    id: '23',
    title: 'FFE India Scholarship',
    department: 'FFE',
    description: 'Tuition + living cost for needy students.',
    eligibility: 'B.Tech/MBBS students',
    link: 'https://ffe.org',
    category: 'Scholarship',
    tags: ['tech', 'mbbs'],
    type: 'Scholarship',
  },
  {
    id: '24',
    title: 'GATE Scholarship',
    department: 'MHRD',
    description: '₹12,400 per month for M.Tech students.',
    eligibility: 'Valid GATE score',
    link: 'https://education.gov.in',
    category: 'Scholarship',
    tags: ['gate'],
    type: 'Scholarship',
  },
  {
    id: '25',
    title: 'Nikon Scholarship',
    department: 'Nikon India',
    description: '₹1L for photography/design courses.',
    eligibility: 'Creative field students',
    link: 'https://buddy4study.com',
    category: 'Scholarship',
    tags: ['design'],
    type: 'Scholarship',
  },
  {
    id: '26',
    title: 'HDFC Parivartan ECS Scholarship',
    department: 'HDFC Bank',
    description: '₹15k to ₹75k for underprivileged students.',
    eligibility: 'Income < ₹3L',
    link: 'https://buddy4study.com',
    category: 'Scholarship',
    tags: ['hdfc'],
    type: 'Scholarship',
  },
  {
    id: '27',
    title: 'ONGC Scholarship for Meritorious Students',
    department: 'ONGC',
    description: '₹48,000 annually for selected courses.',
    eligibility: 'Engineering/MBBS/MBA/Geology',
    link: 'https://www.ongcscholar.org',
    category: 'Scholarship',
    tags: ['merit'],
    type: 'Scholarship',
  },
  {
    id: '28',
    title: 'Aditya Birla Scholarship',
    department: 'Aditya Birla Group',
    description: '₹1.8L per annum for MBA/Law students.',
    eligibility: 'Select institutes',
    link: 'https://www.adityabirlascholars.net',
    category: 'Scholarship',
    tags: ['mba', 'law'],
    type: 'Scholarship',
  },
  {
    id: '29',
    title: 'Sitaram Jindal Scholarship',
    department: 'SJF',
    description: '₹500–₹3,200 monthly for low-income students.',
    eligibility: 'Income < ₹4L',
    link: 'http://www.sitaramjindalfoundation.org',
    category: 'Scholarship',
    tags: ['jindal'],
    type: 'Scholarship',
  },
  {
    id: '30',
    title: 'Sashakt Scholarship',
    department: 'Dr. Reddy’s Foundation',
    description: '₹2.4L for 3 years for B.Sc. girls.',
    eligibility: 'B.Sc. + Female',
    link: 'https://www.sashaktscholarship.org',
    category: 'Scholarship',
    tags: ['female', 'science'],
    type: 'Scholarship',
  },
  {
    id: '31',
    title: 'ONGC SC/ST Scholarship',
    department: 'ONGC',
    description: '₹48,000 per annum for SC/ST students.',
    eligibility: 'SC/ST category',
    link: 'https://www.ongcscholar.org',
    category: 'Scholarship',
    tags: ['sc', 'st'],
    type: 'Scholarship',
  },
  {
    id: '32',
    title: 'Tata Trusts Scholarship',
    department: 'Tata Trusts',
    description: 'Scholarships for various courses.',
    eligibility: 'As per course',
    link: 'https://www.tatatrusts.org',
    category: 'Scholarship',
    tags: ['trust'],
    type: 'Scholarship',
  },
  {
    id: '33',
    title: 'Fair and Lovely Foundation Scholarship',
    department: 'Fair and Lovely Foundation',
    description: '₹25k–₹1L for girls from low-income families.',
    eligibility: 'Female, income < ₹3L',
    link: 'https://www.fairandlovelyfoundation.in',
    category: 'Scholarship',
    tags: ['female'],
    type: 'Scholarship',
  },
];
import { LeaderboardUser } from './types';

export const LEADERBOARD_DATA: LeaderboardUser[] = [
  {
    rank: 1,
    name: 'Ravi Sharma',
    location: 'Delhi',
    tokens: 150,
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
  },
  {
    rank: 2,
    name: 'Neha Verma',
    location: 'Mumbai',
    tokens: 140,
    avatarUrl: 'https://i.pravatar.cc/150?img=2',
  },
  {
    rank: 3,
    name: 'Amit Kumar',
    location: 'Kolkata',
    tokens: 130,
    avatarUrl: 'https://i.pravatar.cc/150?img=3',
  },
];
import { RedeemPerk } from './types';

export const REDEEM_PERKS: RedeemPerk[] = [
  {
    id: '1',
    name: 'Free Counseling Session',
    description: 'Get expert advice on scholarship applications.',
    price: 30,
    icon: () => <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>,
  },
  {
    id: '2',
    name: 'Resume Review',
    description: 'Improve your resume for scholarship interviews.',
    price: 50,
    icon: () => <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" /></svg>,
  },
  {
    id: '3',
    name: 'Priority Support',
    description: 'Get faster support from our team.',
    price: 20,
    icon: () => <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M12 20c4.418 0 8-3.582 8-8s-3.582-8-8-8-8 3.582-8 8 3.582 8 8 8z" /></svg>,
  }
];
